---
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: "30 0 * * *"

# For info on the OS versions, architecture, etc., see
# https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories

jobs:
  test-linux:
    strategy:
      fail-fast: false
      matrix:
        image: [ubuntu:24.04, debian:bookworm]
        os: [ubuntu_x64_8_cores, ubuntu_arm64_8_core]
        include:
          - image: archlinux:latest
            os: ubuntu_x64_8_cores
    runs-on: ${{ matrix.os }}
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Check OS info
        run: |
          uname -a

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run Test OxCaml action
        uses: ./.github/actions/test-oxcaml
        with:
          ocaml-compiler: ocaml-variants.5.2.0+ox
          opam-disable-sandboxing: true

  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-13, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run Test OxCaml action
        uses: ./.github/actions/test-oxcaml
        with:
          ocaml-compiler: ocaml-variants.5.2.0+ox
